### ISSUE TITLE
Icon fields within a matrix field are initially unstyled drop-downs

### ISSUE THREAD

**Issue by dstrunk** [fruitstudios/Icons#4]
See title; basically this means you aren't able to see an icon until the entry, global, etc. is saved.

Steps to reproduce:
---

1. Add matrix field
2. Add Icon field type within a created block
3. Add matrix field to entry
4. add new entry and create a new block with icon field

**Comment by theskyfloor** [comment]
Having this same issue!

**Comment by samhibberd** [comment]
We have a new version being tested which addresses this issue.

**Comment by justjoolz** [comment]
Same thing happens in supertable, note the styled icon browser works fine for existing entries and changing their content only on new 'blocks' etc.

**Comment by samhcorney** [comment]
Hey guys. Thank-you for the feedback! Bug has been fixed in the latest release (0.9.5).

**Comment by dstrunk** [comment]
nice! :+1:
