### ISSUE TITLE
Ionicons

### ISSUE THREAD

**Issue by spotd** [fruitstudios/Icons#6]
How can i use Ionicons? It always reverts back to Fontawsome when saving within a matrix.

**Comment by samhibberd** [comment]
Hi there, the current version only supports font awesome, we have a new version currently being tested which supports most of the common icon fonts. It will also support custom fonts, but probably not for the next realease.

**Comment by ben-callaway** [comment]
Hello,

I'm out of the office on annual leave, back Monday 18th April. All emails will be dealt with on my return.

If you do have anything urgent, please don’t hesitate to get in contact with the team on 01962 809 103 or

Sam Hibberd
sam@fruitstudios.co.uk

Sean Hill
sean@fruitstudios.co.uk

Sam Corney
samc@fruitstudios.co.uk

Thank you.

Kind regards,
Ben Callaway
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
Hampshire
SO23 9AH
 
T: 01962 809 103 
E: ben@fruitstudios.co.uk
W: www.fruitstudios.co.uk

====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Ben Callaway, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================
